# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5d5dfdd928be7ea7f04d6fb36d33b25fc121ea915a79b50a171fab24d74ad45330d90253f6a67e086f3427ecd703d710b965d19473c00f5027b6a37d8dc309c

test:
  secret_key_base: fdc3d1de09b2267ab582d9dff61d1faab1d2776d5f41b4d9ec33650924d2f66608811e462d25903f4f7460365a2dba5324e67e944ad94e2375cac9a97a02fc33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
